### ISSUE TITLE
[FEATURE]Review User Stories

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Product#10]
**Action Required**
Evaluate user stories that have been defined and prioritize what needs to be implemented.

**Comment by morelmiles** [comment]
I've started working on the wireframes

**Comment by onabright** [comment]
This is noted

**Comment by MutegekiHenry** [comment]
Are we still using this repo?

**Comment by onabright** [comment]
@MutegekiHenry As soon as this task is completed I am going to archive this repo. All action will be happening in the Frontend and Backend repos.
