### ISSUE TITLE
[FEATURE] Research about the domain and what data will need to be collected

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Product#2]
**Actions required**
Depending on the domain agreed upon, do research on what type of data will need to be collected necessary to measure the indicator to be innovated. 
Define the data that will need to be captured into the application.

**Comment by philbertobuchel** [comment]
Thanks well received

**Comment by onabright** [comment]
We need to defined the variables that will be necessary to measure the statistic: **Distribution of proportion of urban population living in slums, informal settlements or inadequate housing**

**Comment by onabright** [comment]
I have clearly indicated the data points we shall need capture. Lets build on this. Refer to our working doc. @geneowak @victor-otim @Sulaiman-Mozes

**Comment by onabright** [comment]
The data points have been added to the working doc. If there are no further additions to the variables, I am closing this issue. We shall continue to enhance/tweak as we move along.
