### ISSUE TITLE
[FEATURE] Database design

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Product#4]
**Action Required**
Document the database tables, columns, constraints and table relationships for the application.
Also document the: 
- Models
- Controllers

**Comment by philbertobuchel** [comment]
Hello @Brightonapito IAM a little bit confused were am I going to design
the database. The way I have been designing them was by use of phpmy sql
and hosting them on wamp server so this time round I believe their is
another format or way of designing it please advice



Philbert Geoffrey Obuchel
PIM
CCNA
ORACLE 11G
DCIT
BIT

**Comment by onabright** [comment]
@philbertobuchel by "design" I mean to document the tables. If possible we can even create a high-level entity-relationship diagram. We should do this before creating the actual migrations/tables. 
Remember that for this project we are using Laravel to create the migrations. You need to familiarize yourself with Laravel if it is new to you.

**Comment by geneowak** [comment]
@philbertobuchel, don't worry about the DBMS... For now just layout the tables and the columns they'll contain, that should be enough....

**Comment by philbertobuchel** [comment]
@Eugeneowak
IAM totally stuck  my PC needs to be set up it's even rejecting the
composer setup so IAM still trying to set it up

Philbert Geoffrey Obuchel
PIM
CCNA
ORACLE 11G
DCIT
BIT

**Comment by geneowak** [comment]
@philbertobuchel, you don't need your PC to make the db design... A paper sketch is with the table names with their columns and the data type of each column is good enough.

**Comment by onabright** [comment]
I am moving this issue to the backend repo.
