### ISSUE TITLE
[FEATURE] Setup development tools

### ISSUE THREAD

**Issue by onabright** [BuildForSDG/Team-269-Product#5]
**Action Required**
Configure the development stack (Laravel for backend and ReactJs + ChartsJs)

**Comment by onabright** [comment]
As agreed, I am going to create two separate repos for front end and backend dev tasks.

**Comment by pearlonzo** [comment]
okay

**Comment by geneowak** [comment]
@onabright cool, let us know when done...
for the ui you can setup a brand new react project with the latest version and the same for the api, a brand new Laravel 7 project

**Comment by onabright** [comment]
I have set up both frontend and backend repos.  @pearlonzo @morelmiles and @nserekoallan please review the PR on the frontend repo.
